### PR TITLE
AUT-124: update to debian bookworm & golang 1.22.5

### PR DESCRIPTION
**Pull request by bhearsum**

### CODE REVIEW

**Comment by bhearsum** [comment]
I just noticed the work in #307 and #308 will be touching the build. I'm going to hold off doing anything further until that's done. I'm also going to try to sync things up with the enhancements done in https://github.com/mozilla-services/autograph/pull/898.

**Comment by jmhodges** [comment]
Nah, don't wait. I was just futzing. Both are blocked by the apksigner, I believe, being out of date. Just ship if this doesn't hit that problem

**Comment by jmhodges** [comment]
I use Drafts to represent work in progress that shouldn't block folks

**Comment by bhearsum** [comment]
Closing this in favour of #310 - building from forks is not enabled in CircleCI.

**Pull request closed without merging**
